version: "3.9"

services:
  server:
    build: .
    ports:
      - 8000:8000
  db:
    image: "postgres"
    ports:
      - "4321:5432"
    environment:
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "1234"
    volumes:
      - data:/var/lib/postgresql/data
      - /Users/nasir/thm-pwa/back-end/pgDockerVolume:/server/pgDockerVolume

volumes:
  data:
